/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dictinariess;

import static dictinariess.Dictionary.WORD;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import com.sun.speech.freetts.*;
import java.awt.Dialog;
/**
 *
 * @author Hoang Vu Huong
 */
public class DictionaryApplication extends javax.swing.JFrame {
    
    Dictionary dic = new Dictionary();
    static DefaultListModel dlmEnglish = new DefaultListModel();

    //int size = WORD.size();
    /**
     * Creates new form DemoDAD
     */
    public DictionaryApplication() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        dic.insert();
        for(Word ele : Dictionary.WORD){
            dlmEnglish.addElement(ele.getWord_target());
            ThanhChuaTu.setModel(dlmEnglish);
        }
        this.addWindowListener(new WindowAdapter() {
            public void windowColsing(WindowEvent e) {
                new DictionaryManagement().dictionaryExportToFile("dictionaries.txt");
                System.exit(0);
            }
        });
//        SoLuongTu.setText("Số từ đang có: " + String.valueOf(Dictionary.size));
        // System.out.println(SoLuongTu.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Them = new javax.swing.JButton();
        XoaTu = new javax.swing.JButton();
        TimKiem = new javax.swing.JButton();
        Thoat = new javax.swing.JButton();
        OTimKiem = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        HienThi = new javax.swing.JTextArea();
        PhatAm = new javax.swing.JButton();
        SoLuongTu = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ThanhChuaTu = new javax.swing.JList<>();
        ChangerWord = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hoang Vu Huong");
        setBackground(new java.awt.Color(255, 255, 255));

        Them.setBackground(new java.awt.Color(102, 255, 255));
        Them.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dictinariess/Plus.png"))); // NOI18N
        Them.setText("Thêm Từ");
        Them.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Them.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ThemMouseClicked(evt);
            }
        });

        XoaTu.setBackground(new java.awt.Color(102, 255, 255));
        XoaTu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        XoaTu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dictinariess/delete.png"))); // NOI18N
        XoaTu.setText("Xoá Từ");
        XoaTu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XoaTuMouseClicked(evt);
            }
        });

        TimKiem.setBackground(new java.awt.Color(102, 102, 255));
        TimKiem.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        TimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dictinariess/tải xuống.png"))); // NOI18N
        TimKiem.setText("Tìm kiếm");
        TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimKiemActionPerformed(evt);
            }
        });

        Thoat.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dictinariess/aaaaa.png"))); // NOI18N
        Thoat.setText("Thoát");
        Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThoatActionPerformed(evt);
            }
        });

        OTimKiem.setText("Nhập từ cần tìm...");
        OTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OTimKiemMouseClicked(evt);
            }
        });
        OTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                OTimKiemKeyReleased(evt);
            }
        });

        HienThi.setBackground(new java.awt.Color(255, 255, 204));
        HienThi.setColumns(20);
        HienThi.setRows(5);
        jScrollPane2.setViewportView(HienThi);

        PhatAm.setBackground(new java.awt.Color(102, 255, 255));
        PhatAm.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        PhatAm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dictinariess/loa.png"))); // NOI18N
        PhatAm.setText("UK");
        PhatAm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhatAmActionPerformed(evt);
            }
        });

        SoLuongTu.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        SoLuongTu.setForeground(new java.awt.Color(255, 102, 102));
        SoLuongTu.setText("DICTIONARY ENGLISH - VIETNAM");
        SoLuongTu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ThanhChuaTu.setBackground(new java.awt.Color(102, 255, 204));
        ThanhChuaTu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ThanhChuaTuMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(ThanhChuaTu);

        ChangerWord.setBackground(new java.awt.Color(102, 255, 255));
        ChangerWord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dictinariess/change.png"))); // NOI18N
        ChangerWord.setText("Sửa Từ");
        ChangerWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangerWordActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dictinariess/API.png"))); // NOI18N
        jButton1.setText("API");
        jButton1.setPreferredSize(new java.awt.Dimension(79, 34));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TimKiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3))
                .addGap(157, 157, 157)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(Them)
                        .addGap(18, 18, 18)
                        .addComponent(XoaTu, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PhatAm)
                        .addGap(18, 18, 18)
                        .addComponent(ChangerWord))
                    .addComponent(jScrollPane2)))
            .addGroup(layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(SoLuongTu, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Thoat)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SoLuongTu, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Them, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(XoaTu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PhatAm, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(OTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ChangerWord, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimKiemActionPerformed
        // TODO add your handling code here:
        for (Word ele : Dictionary.WORD) {
            if (ele.getWord_target().equals(OTimKiem.getText())) {
                HienThi.setText(ele.getWord_explain());
                return;
            }
        }
        JOptionPane.showMessageDialog(rootPane, "Từ không có trong từ điển, vui lòng thêm từ mới!");
        new AddNewWord(this, true).setVisible(true);

    }//GEN-LAST:event_TimKiemActionPerformed

    private void ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThoatActionPerformed
        // TODO add your handling code here:
        new DictionaryManagement().dictionaryExportToFile("dictionaries.txt");
        System.exit(0);
    }//GEN-LAST:event_ThoatActionPerformed

    private void OTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OTimKiemMouseClicked
        // TODO add your handling code here:
        OTimKiem.setText("");
        HienThi.setText("");

    }//GEN-LAST:event_OTimKiemMouseClicked

    private void ThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThemMouseClicked
        // TODO add your handling code here:
        //new AddNewWord().setVisible(true);
        new AddNewWord(this, true).setVisible(true);
        
    }//GEN-LAST:event_ThemMouseClicked
    public void AddThanhChuaTu(){
        this.ThanhChuaTu.setModel(dlmEnglish);
    }
    private void XoaTuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XoaTuMouseClicked
        // TODO add your handling code here:
//        boolean check;
//        check = false;
        String s = JOptionPane.showInputDialog("Nhập Từ Cần Xoá");
        if ("".equals(s)) {
            JOptionPane.showMessageDialog(rootPane, "Hãy Nhập Một Từ");
        } else {
            int index = 0;
            for (Word ele : Dictionary.WORD) {
                if (ele.getWord_target().equals(s)) {
                    WORD.remove(index);
                    dlmEnglish.remove(index);
                    ThanhChuaTu.setModel(dlmEnglish);
                    HienThi.setText("");
                    //check = true;
                    return;
                }
                index++;
            }
            //if(check==false) {
            JOptionPane.showMessageDialog(rootPane, "Không Có Từ Cần Xoá");
            //}
        }
    }//GEN-LAST:event_XoaTuMouseClicked

    private void OTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OTimKiemKeyReleased
        // TODO add your handling code here:
        dlmEnglish.clear();
        String S = OTimKiem.getText().toLowerCase();
        Dictionary.WORD.stream().filter((ele) -> (ele.getWord_target().indexOf(S) == 0)).forEachOrdered((ele) -> {
            dlmEnglish.addElement(ele.getWord_target());
        });
        ThanhChuaTu.setModel(dlmEnglish);
    }//GEN-LAST:event_OTimKiemKeyReleased

    private void ThanhChuaTuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThanhChuaTuMouseClicked
        // TODO add your handling code here:
        for (Word ele : Dictionary.WORD) {
            if (ele.getWord_target().equals(ThanhChuaTu.getSelectedValue())) {
                HienThi.setText(ele.getWord_explain());
                return;
            }
        }
    }//GEN-LAST:event_ThanhChuaTuMouseClicked
    private static final String VOICENAME = "kevin16";
    private void PhatAmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhatAmActionPerformed
        // TODO add your handling code here:
        Voice voice;
        VoiceManager vm = VoiceManager.getInstance();
        voice = vm.getVoice(VOICENAME);
        
        voice.allocate();
        try {
            if(ThanhChuaTu.getSelectedValue().equals(""))
                return;
            else
            voice.speak(ThanhChuaTu.getSelectedValue());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_PhatAmActionPerformed

    private void ChangerWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangerWordActionPerformed
        // TODO add your handling code here:
        new ChangerWord(this, true).setVisible(true);
    }//GEN-LAST:event_ChangerWordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new API(this, true).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                    
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new DictionaryApplication().setVisible(true);
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChangerWord;
    private javax.swing.JTextArea HienThi;
    private javax.swing.JTextField OTimKiem;
    private javax.swing.JButton PhatAm;
    private javax.swing.JLabel SoLuongTu;
    private javax.swing.JList<String> ThanhChuaTu;
    private javax.swing.JButton Them;
    private javax.swing.JButton Thoat;
    private javax.swing.JButton TimKiem;
    private javax.swing.JButton XoaTu;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
